# Generated by Django 3.0.4 on 2020-05-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('velocidad_maxima', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('comentario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='estacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('precio_galon_corriente', models.IntegerField(blank=True, default=0, null=True)),
                ('precio_galon_extra', models.IntegerField(blank=True, default=0, null=True)),
                ('precio_galon_acpm', models.IntegerField(blank=True, default=0, null=True)),
                ('precio_metro_cubico_gas', models.IntegerField(blank=True, default=0, null=True)),
                ('comentario', models.CharField(max_length=200)),
            ],
        ),
    ]
