# Generated by Django 3.0.3 on 2020-04-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('tipo_camara', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='estacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('precio_galon', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
