# Generated by Django 3.0.4 on 2020-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, max_length=100)),
                ('lng', models.FloatField(blank=True, max_length=100)),
                ('velocidad_maxima', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures')),
                ('comentario', models.CharField(max_length=200)),
                ('item_aprobado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='estacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, max_length=100)),
                ('lng', models.FloatField(blank=True, max_length=100)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('precio_galon_corriente', models.IntegerField(blank=True, default=0, null=True)),
                ('precio_galon_extra', models.IntegerField(blank=True, default=0, null=True)),
                ('precio_galon_acpm', models.IntegerField(blank=True, default=0, null=True)),
                ('precio_metro_cubico_gas', models.IntegerField(blank=True, default=0, null=True)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures')),
                ('comentario', models.CharField(max_length=200)),
                ('item_aprobado', models.BooleanField()),
            ],
        ),
    ]
