# Generated by Django 3.0.4 on 2020-05-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('We_Driver_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures'),
        ),
    ]
