# Generated by Django 3.0.4 on 2020-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('We_Driver_app', '0002_auto_20200404_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
    ]
